spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: DBAdmin
    password: xbfirst
    
  jpa: 
    properties: 
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        id: 
          new_generator_mappings: false
      
server:
  port: 8799

logging:
  level: 
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/