server:
  port: 8794

spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags:
          - version=0.1
          - author=xiaobin

opentracing.jaeger.http-sender.url: http://localhost:14268/api/traces
opentracing.jaeger.log-spans: true